intel_results_enabled = "Identity & Perso1, Identity & Perso2, Identity & Perso3, Identity & Perso4, Identity & Perso5"
intel_prompts_list = "Identity & Perso, Identity & Perso1, Identity & Perso2, Identity & Perso3, Identity & Perso4, Identity & Perso5, Challenges, Challenges1, Challenges2, Challenges3, Challenges4, Challenges5, SuperPowersFull, SuperPowers1, SuperPowers2, SuperPowers3, SuperPowers4, SuperPowers5, SuperPowers6, SuperPowers7, SuperPowers8, SuperPowers9, Life Mission, Life Mission1, Life Mission2, Life Mission3, Life Mission4, Life Mission5, Holi Full, Holi1, Holi2, Holi3, Holi4, Holi5, Predictions, Predictions1, Predictions2, Predictions3, Predictions4, Predictions5"
intel_prompts_enabled = "Identity & Perso1, Identity & Perso2, Identity & Perso3, Identity & Perso4, Identity & Perso5"

slides_titles = "Ton Identité & Personnalité, Ton Identité Fondamentale : Découvre Ton Essence, Ton Côté Émotionnel : (Re)Découvre Ton Intérieur, Ta Personnalité : Découvre Ton Côté Social, Nos Suggestions de Livres, Conclusion, Tes Défis de Vie et Opportunités de Croissance, Apprendre du Passé et Accueillir le Changement, Tes Chakras Énergétiques Difficiles, Transformer les Conflits en Harmonie Partie 1, Transformer les Conflits en Harmonie Partie 2, Tes Défis Comportementaux, ✮ Tes SuperPouvoirs ✮, Ton SuperPouvoir Principal, Ton Deuxième SuperPouvoir, Ton Troisième SuperPouvoir, Ton Quatrième SuperPouvoir, Ton Cinquième SuperPouvoir, Ton Sixième SuperPouvoir, Ton Septième SuperPouvoir, Ton Huitième SuperPouvoir, Ton Neuvième SuperPouvoir, Ta Mission de Vie, Ton Voyage d'Âme, Ton Parcours d'Évolution Personnelle, Ton Chemin de Vie, Ta Mission de Vie, Questions à Méditer et Actions à Entreprendre, Tes Suggestions Holistiques, Tes Suggestions Holistiques sur l'Amour et les Relations, Tes Suggestions Holistiques sur la Vie Professionnelle, Tes Suggestions Holistiques sur la Santé et le Bien-être, Tes Suggestions Holistiques sur la Spiritualité, Notre Voyage Ensemble ne fait que Commencer, BONUS : Timing Personnel, Ton Année Actuelle, Ton Année Prochaine, Tes Prévisions Mensuelles, Tes Prévisions Mensuelles, Tes Prévisions Mensuelles, Tes Prévisions Mensuelles"
slides_subtitles = "Image holistique de qui tu es, Obstacles sur le chemin de ton voyage de vie, Comprendre tes dons & talents uniques, Ta véritable vocation pour avoir un impact positif dans le monde, Auto-réflexions et Actions pour Grandir, Prédictions pour ton année personnelle"

slides_introductions = """Welcome to the profound exploration of your Identity & Personality. This stage of your journey is like an intricate dance, where the cosmos and numbers twirl together to reveal your authentic self. As your unseen guides, we will lead you into the heart of this dance, unveiling its meaning, rhythm, and resonance.
Prepare to journey within, where the unique terrain of your Identity & Personality unfolds. This exploration is the cornerstone of your Holistic Reading, delving into your inherent nature as revealed through Astrology, Numerology, and Human Design.
Here, you are not just another name or face in the crowd, {first_name}. You are an exquisite mosaic, with each piece a unique vibration, a celestial whisper, an energetic echo, all weaving together to form the divine masterpiece that is you.
The first step of your journey uncovers your core nature—your indomitable spirit that propels you forward and the beating heart of your ambitions. It's your motivation, the force behind your actions, desires, and dreams. As we explore the depths of your identity, you'll reconnect with the driving factors shaping your life, offering profound insights into the forces influencing your journey.
Next, we shed light on your inner self—your emotional sanctuary. This is your fortress of solitude, where you retreat to be alone with your thoughts. Here, {first_name}, within the confines of your inner world, you will discover how you process emotions and what constitutes your comfort zone. Understanding this emotional architecture will help you navigate the labyrinth of your feelings, recognize your triggers, and find what brings you solace.
The final layer of your Identity & Personality is how you present yourself to the outside world—the mask you wear, consciously or unconsciously, and the impression you leave on others. This projection reflects your self-perception and the way you view the world around you. Through this exploration, you'll better understand the impression you create and how the world responds to you.
Embarking on this journey promises a treasure trove of self-knowledge, ready to be uncovered. Within these revelations, you'll find a deeper connection with yourself and an empowered perspective for navigating life's complexities. Take a deep breath, open your heart, and step boldly into the adventure of self-discovery. Your exploration begins now, in the vibrant realms of your Identity & Personality."""